export { mergeStyle, style2string } from './mergeStyle';
export { get } from './get';
export { getTextProps, setTextProps, toggleTextProps } from './text';
export { toggleBlock, getBlockProps, setBlockProps, isBlockActive, clearBlockProps } from './block';
export { withPlugins } from './withPlugins';
export { isStart } from './isStart';
export { promiseUploadFunc } from './promiseUploadFunc';
export { base64file } from './base64file';
export { mergeLocalteFromPlugins } from './mergeLocalteFromPlugins';
export { isEmpty } from './isEmpty';
